# Generated by Django 4.1.1 on 2022-09-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('ценнаяМЦ', 'ценная МЦ'), ('малоценнаяМЦ', 'малоценная МЦ'), ('спецодежда', 'спецодежда')], max_length=15, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
