# Generated by Django 4.1.1 on 2022-09-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_material_options_material_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ценные МЦ', 'Ценные МЦ'), ('Малоценные МЦ', 'Малоценные МЦ'), ('Спецодежда', 'Спецодежда')], max_length=60)),
            ],
        ),
    ]
