# Generated by Django 4.1.1 on 2022-09-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_material_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
    ]
