# Generated by Django 4.1.1 on 2022-09-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_rename_category_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('note', models.TextField(verbose_name='Содержание')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.category', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='material',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='material',
            name='length',
            field=models.PositiveIntegerField(verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='material',
            name='note',
            field=models.TextField(verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='material',
            name='organization',
            field=models.CharField(max_length=50, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Стоимость за еденицу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='serial',
            field=models.CharField(max_length=20, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='material',
            name='size',
            field=models.CharField(max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='material',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='material',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.document', verbose_name='Номер и дата документа'),
        ),
    ]
