# Generated by Django 4.1.1 on 2022-09-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_material_document_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_material', models.CharField(max_length=20, null=True, verbose_name='Вид товара')),
                ('numb_seral', models.CharField(max_length=20, null=True, verbose_name='Номер инвентарной карты')),
                ('face', models.CharField(max_length=150, null=True, verbose_name='Приянял МЦ')),
                ('lifetime', models.PositiveIntegerField(null=True, verbose_name='Срок полезного использования (мес)')),
                ('details', models.TextField(null=True, verbose_name='Описание составляющих и характеристик')),
                ('transfer', models.CharField(max_length=150, null=True, verbose_name='Место эксплуатации')),
                ('work', models.TextField(null=True, verbose_name='Описание работы')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.material', verbose_name='Товар')),
            ],
        ),
    ]
