# Generated by Django 4.1.1 on 2022-09-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_serialmodel_details_alter_serialmodel_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialmodel',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.material', verbose_name='Товар'),
        ),
    ]
